apiVersion: v1
kind: Pod
metadata:
  name: first
spec: 
  containers: 
  - name: nginx
    image: nginx
    volumeMounts:
    -  mountPath: "/var/www/html"
       name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: myclaim
      
